library(rpart)
library(rpart.plot)
DataAct<-read.csv(file.choose(),header=T,sep=',')
str(DataAct)
model<-rpart(CODE_Medical~ ., DataAct,method="class")
print(model)
plot(model,uniform=TRUE,main="Classification Tree with rpart")
plotcp(model)
prp(model,extra=1)
predict(model, type="class")
table(DataAct$CODE_Medical, predict(model, type="class"))
